---
title: "differential peak analysis"
author: "Melissa Aldana"
date: "2023-06-22"
output: html_document
---

```{r}
# To Solve issues regarding the installation of diffbind and magrittr.

#if (!require("BiocManager", quietly = TRUE))
#    install.packages("BiocManager")
#BiocManager::install(version = "3.16",type='source')
#BiocManager::install("DiffBind",force = TRUE)
#BiocManager::install("magrittr",type="source",force = TRUE)
#BiocManager::version()
# To remove all previously downloaded packages
#installed_packages <- installed.packages()[,"Package"]
#for (package in installed_packages) {
#  remove.packages(package,lib=.libPaths()[1])
#}

```


```{r}
library(DiffBind)
library(magrittr)
#library(GenomicRanges)
```

```{r}
#macs2 compare to yw
#1
#Diffbind for CLAMP deltaDE-deltaDE vs yw males

# read in data sheet
df <- read.csv('/Users/zhangchengyue/Desktop/CnR/DiffBind/macs2/input_csv/CLAMP_deltaDE-deltaDE_vs_yw_males_dedup.csv')
sample.df <- dba(sampleSheet=df)

#blacklist.df <- read.table('/users/czhang91/CnR_2023/genome/dm6-blacklist.bed', col.names = c('chr', 'start', 'end'))
#blacklist.gr <- makeGRangesFromDataFrame(blacklist.df, keep.extra.columns = FALSE)

# sanity check 
#plot(sample.df)
#dba.plotPCA(sample.df)

# run diffbind
DE.clamp_mutant_dataset <- sample.df %>% 
  dba.blacklist(blacklist = TRUE, greylist = FALSE)  %>%
  dba.count(summits = 250)     %>%
  dba.normalize() %>%
  dba.contrast(contrast = c("Condition", "znf", "wt"))  %>%
  dba.analyze(method = DBA_DESEQ2)

#how to save dba
dba.save(DE.clamp_mutant_dataset,'CLAMP_deltaDE-deltaDE_vs_yw_males')

# volcano plot
png(file='/Users/zhangchengyue/Desktop/CnR/DiffBind/macs2/plots/CLAMP_deltaDE-deltaDE_vs_yw_males.png',width=6, height=4, units='in', pointsize = 20, res=350)
dba.plotVolcano(DE.clamp_mutant_dataset)
dev.off()

# report of DE analysis
report <- dba.report(DE.clamp_mutant_dataset)
report.df <- as.data.frame(report)
write.table(report.df, "CLAMP_deltaDE-deltaDE_vs_yw_males.tsv", sep = "\t", quote = FALSE, row.names = FALSE)
```


```{r}
#2
#Diffbind for CLAMP deltaDH-deltaDH vs yw males

# read in data sheet
df <- read.csv('/Users/zhangchengyue/Desktop/CnR/DiffBind/macs2/input_csv/CLAMP_deltaH-deltaH_vs_yw_males_dedup.csv')
sample.df <- dba(sampleSheet=df)

# sanity check 
plot(sample.df)
dba.plotPCA(sample.df)

# run diffbind
DE.clamp_mutant_dataset <- sample.df %>% 
  dba.blacklist(blacklist = TRUE,greylist = FALSE)  %>%
  dba.count(summits = 250)     %>%
  dba.normalize() %>%
  dba.contrast(contrast = c("Condition", "msl2", "wt"))  %>%
  dba.analyze(method = DBA_DESEQ2)

#how to save dba
dba.save(DE.clamp_mutant_dataset,'CLAMP_deltaH-deltaH_vs_yw_males')

# volcano plot
png(file='/Users/zhangchengyue/Desktop/CnR/DiffBind/macs2/plots/CLAMP_deltaH-deltaH_vs_yw_males.png',width=6, height=4, units='in', pointsize = 20, res=350)
dba.plotVolcano(DE.clamp_mutant_dataset)
dev.off()

# report of DE analysis
report <- dba.report(DE.clamp_mutant_dataset)
report.df <- as.data.frame(report)
write.table(report.df, "CLAMP_deltaH-deltaH_vs_yw_males.tsv", sep = "\t", quote = FALSE, row.names = FALSE)
```

```{r}
#3
#Diffbind for MSL2 clampDE-clampDE vs yw males

# read in data sheet
df <- read.csv('/Users/zhangchengyue/Desktop/CnR/DiffBind/macs2/input_csv/MSL2_clampDE-clampDE_vs_yw_males_dedup.csv')
sample.df <- dba(sampleSheet=df)

# sanity check 
plot(sample.df)
dba.plotPCA(sample.df)

# run diffbind
DE.clamp_mutant_dataset <- sample.df %>% 
  dba.blacklist(blacklist = TRUE,greylist = FALSE)  %>%
  dba.count(summits = 250)     %>%
  dba.normalize() %>%
  dba.contrast(contrast = c("Condition", "znf", "wt"))  %>%
  dba.analyze(method = DBA_DESEQ2)

#how to save dba
dba.save(DE.clamp_mutant_dataset,'MSL2_clampDE-clampDE_vs_yw_males.dba')

# volcano plot
png(file='/Users/zhangchengyue/Desktop/CnR/DiffBind/macs2/plots/MSL2_clampDE-clampDE_vs_yw_males.png',width=6, height=4, units='in', pointsize = 20, res=350)
dba.plotVolcano(DE.clamp_mutant_dataset)
dev.off()

# report of DE analysis
report <- dba.report(DE.clamp_mutant_dataset)
report.df <- as.data.frame(report)
write.table(report.df, "MSL2_clampDE-clampDE_vs_yw_males.tsv", sep = "\t", quote = FALSE, row.names = FALSE)
```



```{r}
#4
#Diffbind for MSL2 clampDH-clampDH vs yw males

# read in data sheet
df <- read.csv('/Users/zhangchengyue/Desktop/CnR/DiffBind/macs2/input_csv/MSL2_clampDH-clampDH_vs_yw_males_dedup.csv')
sample.df <- dba(sampleSheet=df)

# sanity check 
plot(sample.df)
dba.plotPCA(sample.df)

# run diffbind
DE.clamp_mutant_dataset <- sample.df %>% 
  dba.blacklist(blacklist = TRUE,greylist = FALSE)  %>%
  dba.count(summits = 250)     %>%
  dba.normalize() %>%
  dba.contrast(contrast = c("Condition", "msl2", "wt"))  %>%
  dba.analyze(method = DBA_DESEQ2)

#how to save dba
dba.save(DE.clamp_mutant_dataset,'MSL2_clampDH-clampDH_vs_yw_males.dba')

# volcano plot
png(file='/Users/zhangchengyue/Desktop/CnR/DiffBind/macs2/plots/MSL2_clampDH-clampDH_vs_yw_males.png',width=6, height=4, units='in', pointsize = 20, res=350)
dba.plotVolcano(DE.clamp_mutant_dataset)
dev.off()

# report of DE analysis
report <- dba.report(DE.clamp_mutant_dataset)
report.df <- as.data.frame(report)
write.table(report.df, "MSL2_clampDH-clampDH_vs_yw_males.tsv", sep = "\t", quote = FALSE, row.names = FALSE)
```



```{r}
#macs2 compare to heterozygote
#1
#Diffbind for CLAMP deltaDE-deltaDE vs deltaH-CyOtwistGFP males

# read in data sheet
df <- read.csv('/Users/zhangchengyue/Desktop/CnR/DiffBind/CLAMP_deltaDE-deltaDE_vs_deltaH-CyOtwistGFP_males_dedup.csv')
sample.df <- dba(sampleSheet=df)

# sanity check 
plot(sample.df)
dba.plotPCA(sample.df)

# run diffbind
DE.clamp_mutant_dataset <- sample.df %>% 
  dba.blacklist(blacklist = TRUE, greylist = FALSE)  %>%
  dba.count(summits = 250)     %>%
  dba.normalize() %>%
  dba.contrast(contrast = c("Condition", "znf", "msl2/+"))  %>%
  dba.analyze(method = DBA_DESEQ2)

#how to save dba
dba.save(DE.clamp_mutant_dataset,'CLAMP_deltaDE-deltaDE_vs_deltaH-CyOtwistGFP_males')

# volcano plot
png(file='/Users/zhangchengyue/Desktop/CnR/DiffBind/plots/CLAMP_deltaDE-deltaDE_vs_deltaH-CyOtwistGFP_males.png',width=6, height=4, units='in', pointsize = 20, res=350)
dba.plotVolcano(DE.clamp_mutant_dataset)
dev.off()

# report of DE analysis
report <- dba.report(DE.clamp_mutant_dataset)
report.df <- as.data.frame(report)
write.table(report.df, "/Users/zhangchengyue/Desktop/CnR/DiffBind/reports/CLAMP_deltaDE-deltaDE_vs_deltaH-CyOtwistGFP_males.tsv", sep = "\t", quote = FALSE, row.names = FALSE)
```


```{r}
#2
#Diffbind for CLAMP deltaDH-deltaDH vs deltaH-CyOtwistGFP males

# read in data sheet
df <- read.csv('/Users/zhangchengyue/Desktop/CnR/DiffBind/CLAMP_deltaH-deltaH_vs_deltaH-CyOtwistGFP_males_dedup.csv')
sample.df <- dba(sampleSheet=df)

# sanity check 
plot(sample.df)
dba.plotPCA(sample.df)

# run diffbind
DE.clamp_mutant_dataset <- sample.df %>% 
  dba.blacklist(blacklist = TRUE,greylist = FALSE)  %>%
  dba.count(summits = 250)     %>%
  dba.normalize() %>%
  dba.contrast(contrast = c("Condition", "msl2", "msl2/+"))  %>%
  dba.analyze(method = DBA_DESEQ2)

#how to save dba
dba.save(DE.clamp_mutant_dataset,'CLAMP_deltaH-deltaH_vs_deltaH-CyOtwistGFP_males')

# volcano plot
png(file='/Users/zhangchengyue/Desktop/CnR/DiffBind/plots/CLAMP_deltaH-deltaH_vs_deltaH-CyOtwistGFP_males.png',width=6, height=4, units='in', pointsize = 20, res=350)
dba.plotVolcano(DE.clamp_mutant_dataset)
dev.off()

# report of DE analysis
report <- dba.report(DE.clamp_mutant_dataset)
report.df <- as.data.frame(report)
write.table(report.df, "/Users/zhangchengyue/Desktop/CnR/DiffBind/reports/CLAMP_deltaH-deltaH_vs_deltaH-CyOtwistGFP_males.tsv", sep = "\t", quote = FALSE, row.names = FALSE)
```

```{r}
#3
#Diffbind for MSL2 clampDE-clampDE vs clampDH-CyOtwistGFP males

# read in data sheet
df <- read.csv('/Users/zhangchengyue/Desktop/CnR/DiffBind/MSL2_clampDE-clampDE_vs_clampDH-CyOtwistGFP_males_dedup.csv')
sample.df <- dba(sampleSheet=df)

# sanity check 
plot(sample.df)
dba.plotPCA(sample.df)

# run diffbind
DE.clamp_mutant_dataset <- sample.df %>% 
  dba.blacklist(blacklist = TRUE,greylist = FALSE)  %>%
  dba.count(summits = 250)     %>%
  dba.normalize() %>%
  dba.contrast(contrast = c("Condition", "znf", "msl2/+"))  %>%
  dba.analyze(method = DBA_DESEQ2)

#how to save dba
dba.save(DE.clamp_mutant_dataset,'MSL2_clampDE-clampDE_vs_clampDH-CyOtwistGFP_males.dba')

# volcano plot
png(file='/Users/zhangchengyue/Desktop/CnR/DiffBind/plots/MSL2_clampDE-clampDE_vs_clampDH-CyOtwistGFP_males.png',width=6, height=4, units='in', pointsize = 20, res=350)
dba.plotVolcano(DE.clamp_mutant_dataset)
dev.off()

# report of DE analysis
report <- dba.report(DE.clamp_mutant_dataset)
report.df <- as.data.frame(report)
write.table(report.df, "/Users/zhangchengyue/Desktop/CnR/DiffBind/reports/MSL2_clampDE-clampDE_vs_clampDH-CyOtwistGFP_males.tsv", sep = "\t", quote = FALSE, row.names = FALSE)
```



```{r}
#4
#Diffbind for MSL2 clampDH-clampDH vs deltaH-CyOtwistGFP males

# read in data sheet
df <- read.csv('/Users/zhangchengyue/Desktop/CnR/DiffBind/MSL2_clampDH-clampDH_vs_clampDH-CyOtwistGFP_males_dedup.csv')
sample.df <- dba(sampleSheet=df)

# sanity check 
plot(sample.df)
dba.plotPCA(sample.df)

# run diffbind
DE.clamp_mutant_dataset <- sample.df %>% 
  dba.blacklist(blacklist = TRUE,greylist = FALSE)  %>%
  dba.count(summits = 250)     %>%
  dba.normalize() %>%
  dba.contrast(contrast = c("Condition", "msl2", "msl2/+"))  %>%
  dba.analyze(method = DBA_DESEQ2)

#how to save dba
dba.save(DE.clamp_mutant_dataset,'MSL2_clampDH-clampDH_vs_clampDH-CyOtwistGFP_males.dba')

# volcano plot
png(file='/Users/zhangchengyue/Desktop/CnR/DiffBind/plots/MSL2_clampDH-clampDH_vs_clampDH-CyOtwistGFP_males.png',width=6, height=4, units='in', pointsize = 20, res=350)
dba.plotVolcano(DE.clamp_mutant_dataset)
dev.off()

# report of DE analysis
report <- dba.report(DE.clamp_mutant_dataset)
report.df <- as.data.frame(report)
write.table(report.df, "/Users/zhangchengyue/Desktop/CnR/DiffBind/reports/MSL2_clampDH-clampDH_vs_clampDH-CyOtwistGFP_males.tsv", sep = "\t", quote = FALSE, row.names = FALSE)
```




```{r}
#seacr compared to yw
#1
#Diffbind for CLAMP deltaDE-deltaDE vs yw males

# read in data sheet
df <- read.csv('/Users/zhangchengyue/Desktop/CnR/DiffBind/seacr/input_csv/CLAMP_deltaDE-deltaDE_vs_yw_males_dedup.csv')
sample.df <- dba(sampleSheet=df)

# sanity check 
plot(sample.df)
dba.plotPCA(sample.df)

# run diffbind
DE.clamp_mutant_dataset <- sample.df %>% 
  dba.blacklist(blacklist = TRUE, greylist = FALSE)  %>%
  dba.count(summits = 250)     %>%
  dba.normalize() %>%
  dba.contrast(contrast = c("Condition", "znf", "wt"))  %>%
  dba.analyze(method = DBA_DESEQ2)

#how to save dba
dba.save(DE.clamp_mutant_dataset,'CLAMP_deltaDE-deltaDE_vs_yw_males')

# volcano plot
png(file='/Users/zhangchengyue/Desktop/CnR/DiffBind/seacr/plots/CLAMP_deltaDE-deltaDE_vs_yw_males.png',width=6, height=4, units='in', pointsize = 20, res=350)
dba.plotVolcano(DE.clamp_mutant_dataset)
dev.off()

# report of DE analysis
report <- dba.report(DE.clamp_mutant_dataset)
report.df <- as.data.frame(report)
write.table(report.df, "CLAMP_deltaDE-deltaDE_vs_yw_males.tsv", sep = "\t", quote = FALSE, row.names = FALSE)
```


```{r}
#2
#Diffbind for CLAMP deltaDH-deltaDH vs yw males

# read in data sheet
df <- read.csv('/Users/zhangchengyue/Desktop/CnR/DiffBind/seacr/input_csv/CLAMP_deltaH-deltaH_vs_yw_males_dedup.csv')
sample.df <- dba(sampleSheet=df)

# sanity check 
plot(sample.df)
dba.plotPCA(sample.df)

# run diffbind
DE.clamp_mutant_dataset <- sample.df %>% 
  dba.blacklist(blacklist = TRUE,greylist = FALSE)  %>%
  dba.count(summits = 250)     %>%
  dba.normalize() %>%
  dba.contrast(contrast = c("Condition", "msl2", "wt"))  %>%
  dba.analyze(method = DBA_DESEQ2)

#how to save dba
dba.save(DE.clamp_mutant_dataset,'CLAMP_deltaH-deltaH_vs_yw_males')

# volcano plot
png(file='/Users/zhangchengyue/Desktop/CnR/DiffBind/seacr/plots/CLAMP_deltaH-deltaH_vs_yw_males.png',width=6, height=4, units='in', pointsize = 20, res=350)
dba.plotVolcano(DE.clamp_mutant_dataset)
dev.off()

# report of DE analysis
report <- dba.report(DE.clamp_mutant_dataset)
report.df <- as.data.frame(report)
write.table(report.df, "CLAMP_deltaH-deltaH_vs_yw_males.tsv", sep = "\t", quote = FALSE, row.names = FALSE)
```

```{r}
#3
#Diffbind for MSL2 clampDE-clampDE vs yw males

# read in data sheet
df <- read.csv('/Users/zhangchengyue/Desktop/CnR/DiffBind/seacr/input_csv/MSL2_clampDE-clampDE_vs_yw_males_dedup.csv')
sample.df <- dba(sampleSheet=df)

# sanity check 
plot(sample.df)
dba.plotPCA(sample.df)

# run diffbind
DE.clamp_mutant_dataset <- sample.df %>% 
  dba.blacklist(blacklist = TRUE,greylist = FALSE)  %>%
  dba.count(summits = 250)     %>%
  dba.normalize() %>%
  dba.contrast(contrast = c("Condition", "znf", "wt"))  %>%
  dba.analyze(method = DBA_DESEQ2)

#how to save dba
dba.save(DE.clamp_mutant_dataset,'MSL2_clampDE-clampDE_vs_yw_males.dba')

# volcano plot
png(file='/Users/zhangchengyue/Desktop/CnR/DiffBind/seacr/plots/MSL2_clampDE-clampDE_vs_yw_males.png',width=6, height=4, units='in', pointsize = 20, res=350)
dba.plotVolcano(DE.clamp_mutant_dataset)
dev.off()

# report of DE analysis
report <- dba.report(DE.clamp_mutant_dataset)
report.df <- as.data.frame(report)
write.table(report.df, "MSL2_clampDE-clampDE_vs_yw_males.tsv", sep = "\t", quote = FALSE, row.names = FALSE)
```



```{r}
#4
#Diffbind for MSL2 clampDH-clampDH vs yw males

# read in data sheet
df <- read.csv('/Users/zhangchengyue/Desktop/CnR/DiffBind/seacr/input_csv/MSL2_clampDH-clampDH_vs_yw_males_dedup.csv')
sample.df <- dba(sampleSheet=df)

# sanity check 
plot(sample.df)
dba.plotPCA(sample.df)

# run diffbind
DE.clamp_mutant_dataset <- sample.df %>% 
  dba.blacklist(blacklist = TRUE,greylist = FALSE)  %>%
  dba.count(summits = 250)     %>%
  dba.normalize() %>%
  dba.contrast(contrast = c("Condition", "msl2", "wt"))  %>%
  dba.analyze(method = DBA_DESEQ2)

#how to save dba
dba.save(DE.clamp_mutant_dataset,'MSL2_clampDH-clampDH_vs_yw_males.dba')

# volcano plot
png(file='/Users/zhangchengyue/Desktop/CnR/DiffBind/seacr/plots/MSL2_clampDH-clampDH_vs_yw_males.png',width=6, height=4, units='in', pointsize = 20, res=350)
dba.plotVolcano(DE.clamp_mutant_dataset)
dev.off()

# report of DE analysis
report <- dba.report(DE.clamp_mutant_dataset)
report.df <- as.data.frame(report)
write.table(report.df, "MSL2_clampDH-clampDH_vs_yw_males.tsv", sep = "\t", quote = FALSE, row.names = FALSE)
```








```{r}
#macs2 compare to heterozygote
#1
#Diffbind for CLAMP deltaDE-deltaDE vs deltaH-CyOtwistGFP males

# read in data sheet
df <- read.csv('/Users/zhangchengyue/Desktop/CnR/DiffBind/CLAMP_deltaDE-deltaDE_vs_deltaH-CyOtwistGFP_males_dedup.csv')
sample.df <- dba(sampleSheet=df)

# sanity check 
plot(sample.df)
dba.plotPCA(sample.df)

# run diffbind
DE.clamp_mutant_dataset <- sample.df %>% 
  dba.blacklist(blacklist = TRUE, greylist = FALSE)  %>%
  dba.count(summits = 250)     %>%
  dba.normalize() %>%
  dba.contrast(contrast = c("Condition", "znf", "msl2/+"))  %>%
  dba.analyze(method = DBA_DESEQ2)

#how to save dba
dba.save(DE.clamp_mutant_dataset,'CLAMP_deltaDE-deltaDE_vs_deltaH-CyOtwistGFP_males')

# volcano plot
png(file='/Users/zhangchengyue/Desktop/CnR/DiffBind/plots/CLAMP_deltaDE-deltaDE_vs_deltaH-CyOtwistGFP_males.png',width=6, height=4, units='in', pointsize = 20, res=350)
dba.plotVolcano(DE.clamp_mutant_dataset)
dev.off()

# report of DE analysis
report <- dba.report(DE.clamp_mutant_dataset)
report.df <- as.data.frame(report)
write.table(report.df, "/Users/zhangchengyue/Desktop/CnR/DiffBind/reports/CLAMP_deltaDE-deltaDE_vs_deltaH-CyOtwistGFP_males.tsv", sep = "\t", quote = FALSE, row.names = FALSE)
```


```{r}
#2
#Diffbind for CLAMP deltaDH-deltaDH vs deltaH-CyOtwistGFP males

# read in data sheet
df <- read.csv('/Users/zhangchengyue/Desktop/CnR/DiffBind/CLAMP_deltaH-deltaH_vs_deltaH-CyOtwistGFP_males_dedup.csv')
sample.df <- dba(sampleSheet=df)

# sanity check 
plot(sample.df)
dba.plotPCA(sample.df)

# run diffbind
DE.clamp_mutant_dataset <- sample.df %>% 
  dba.blacklist(blacklist = TRUE,greylist = FALSE)  %>%
  dba.count(summits = 250)     %>%
  dba.normalize() %>%
  dba.contrast(contrast = c("Condition", "msl2", "msl2/+"))  %>%
  dba.analyze(method = DBA_DESEQ2)

#how to save dba
dba.save(DE.clamp_mutant_dataset,'CLAMP_deltaH-deltaH_vs_deltaH-CyOtwistGFP_males')

# volcano plot
png(file='/Users/zhangchengyue/Desktop/CnR/DiffBind/plots/CLAMP_deltaH-deltaH_vs_deltaH-CyOtwistGFP_males.png',width=6, height=4, units='in', pointsize = 20, res=350)
dba.plotVolcano(DE.clamp_mutant_dataset)
dev.off()

# report of DE analysis
report <- dba.report(DE.clamp_mutant_dataset)
report.df <- as.data.frame(report)
write.table(report.df, "/Users/zhangchengyue/Desktop/CnR/DiffBind/reports/CLAMP_deltaH-deltaH_vs_deltaH-CyOtwistGFP_males.tsv", sep = "\t", quote = FALSE, row.names = FALSE)
```

```{r}
#3
#Diffbind for MSL2 clampDE-clampDE vs clampDH-CyOtwistGFP males

# read in data sheet
df <- read.csv('/Users/zhangchengyue/Desktop/CnR/DiffBind/MSL2_clampDE-clampDE_vs_clampDH-CyOtwistGFP_males_dedup.csv')
sample.df <- dba(sampleSheet=df)

# sanity check 
plot(sample.df)
dba.plotPCA(sample.df)

# run diffbind
DE.clamp_mutant_dataset <- sample.df %>% 
  dba.blacklist(blacklist = TRUE,greylist = FALSE)  %>%
  dba.count(summits = 250)     %>%
  dba.normalize() %>%
  dba.contrast(contrast = c("Condition", "znf", "msl2/+"))  %>%
  dba.analyze(method = DBA_DESEQ2)

#how to save dba
dba.save(DE.clamp_mutant_dataset,'MSL2_clampDE-clampDE_vs_clampDH-CyOtwistGFP_males.dba')

# volcano plot
png(file='/Users/zhangchengyue/Desktop/CnR/DiffBind/plots/MSL2_clampDE-clampDE_vs_clampDH-CyOtwistGFP_males.png',width=6, height=4, units='in', pointsize = 20, res=350)
dba.plotVolcano(DE.clamp_mutant_dataset)
dev.off()

# report of DE analysis
report <- dba.report(DE.clamp_mutant_dataset)
report.df <- as.data.frame(report)
write.table(report.df, "/Users/zhangchengyue/Desktop/CnR/DiffBind/reports/MSL2_clampDE-clampDE_vs_clampDH-CyOtwistGFP_males.tsv", sep = "\t", quote = FALSE, row.names = FALSE)
```



```{r}
#4
#Diffbind for MSL2 clampDH-clampDH vs deltaH-CyOtwistGFP males

# read in data sheet
df <- read.csv('/Users/zhangchengyue/Desktop/CnR/DiffBind/MSL2_clampDH-clampDH_vs_clampDH-CyOtwistGFP_males_dedup.csv')
sample.df <- dba(sampleSheet=df)

# sanity check 
plot(sample.df)
dba.plotPCA(sample.df)

# run diffbind
DE.clamp_mutant_dataset <- sample.df %>% 
  dba.blacklist(blacklist = TRUE,greylist = FALSE)  %>%
  dba.count(summits = 250)     %>%
  dba.normalize() %>%
  dba.contrast(contrast = c("Condition", "msl2", "msl2/+"))  %>%
  dba.analyze(method = DBA_DESEQ2)

#how to save dba
dba.save(DE.clamp_mutant_dataset,'MSL2_clampDH-clampDH_vs_clampDH-CyOtwistGFP_males.dba')

# volcano plot
png(file='/Users/zhangchengyue/Desktop/CnR/DiffBind/plots/MSL2_clampDH-clampDH_vs_clampDH-CyOtwistGFP_males.png',width=6, height=4, units='in', pointsize = 20, res=350)
dba.plotVolcano(DE.clamp_mutant_dataset)
dev.off()

# report of DE analysis
report <- dba.report(DE.clamp_mutant_dataset)
report.df <- as.data.frame(report)
write.table(report.df, "/Users/zhangchengyue/Desktop/CnR/DiffBind/reports/MSL2_clampDH-clampDH_vs_clampDH-CyOtwistGFP_males.tsv", sep = "\t", quote = FALSE, row.names = FALSE)
```




